cart/urls.py
from django.urls import path
from .import views 

app_name = 'cart'

urlpatterns = [
	path('', views.cart_detail, name='cart_detail'),
	path('add/<int:product_id>/', views.cart_add, name='cart_add'),
	path('remov/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

myshop/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('', include('shop.urls', namespace='shop')),
]

if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path
from .import views

app_name = 'shop'

urlpatterns = [
	path('', views.product_list, name='product_list'),
	path('<slug:category_slug>/', views.product_list, name='product_list_by_category'),
	path('<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),
]

cart/models.py
from django.db import models

# Create your models here.

shop/models.py
from django.db import models
from django.urls import reverse

# Create your models here.

class Category(models.Model):
	name = models.CharField(max_length=255, db_index=True)
	slug = models.SlugField(max_length=255, unique=True)

	class Meta:
		ordering = ['name',]
		verbose_name = 'category'
		verbose_name_plural = 'categories'

	def __str__(self):
		return self.name

	def get_absolute_url(self):
		return reverse('shop:product_list_by_category', args=[self.slug])

class Product(models.Model):
	category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='products')
	name = models.CharField(max_length=255, db_index=True)
	slug = models.SlugField(max_length=255, db_index=True)
	image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)
	description = models.TextField(blank=True)
	price = models.DecimalField(max_digits=10, decimal_places=2)
	available = models.BooleanField(default=True)
	created = models.DateTimeField(auto_now_add=True)
	updated = models.DateTimeField(auto_now=True)

	class Meta:
		ordering = ['name',]
		index_together = (('id', 'slug'),)

	def __str__(self):
		return self.name

	def get_absolute_url(self):
		return reverse('shop:product_detail', args=[self.id, self.slug])

cart/forms.py
from django import forms 

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1,21)]

class CartAddProductForm(forms.Form):
	quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
	update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from shop.models import Product
from .cart import Cart 
from .forms import CartAddProductForm

@require_POST
def cart_add(request, product_id):
	cart = Cart(request)
	product = get_object_or_404(Product, id=product_id)
	form = CartAddProductForm(request.POST)
	if form.is_valid():
		cd = form.cleaned_data
		cart.add(product=product, quantity=cd['quantity'], update_quantity=cd['update'])
	return redirect('cart:cart_detail')


def cart_remove(request, product_id):
	cart = Cart(request)
	product = get_object_or_404(Product, id=product_id)
	cart.remove(product)
	return redirect('cart:cart_detail')

def cart_detail(request):
	cart = Cart(request)
	for item in cart:
		item['update_quantity_form'] = CartAddProductForm(initial={'quantity': item['quantity'], 'update':True})
	return render(request, 'cart/detail.html', {'cart':cart})
# Create your views here.

shop/views.py
from django.shortcuts import render, get_object_or_404
from .models import Category, Product
from cart.forms import CartAddProductForm
# Create your views here.

def product_list(request, category_slug=None):
	category = None
	categories = Category.objects.all()
	products = Product.objects.filter(available=True)
	if category_slug:
		category = get_object_or_404(Category, slug=category_slug)
		products = products.filter(category=category)
	return render(request, 'shop/product/list.html', {'category':category, 'categories':categories, 'products':products})

def product_detail(request, id, slug):
	product = get_object_or_404(Product, id=id, slug=slug, available=True)
	cart_product_form = CartAddProductForm()
	return render(request, 'shop/product/detail.html', {'product':product, 'cart_product_form':cart_product_form})

cart/templates/cart/detail.html
{% extends 'shop/base.html' %}
{% block content %}
<table class="table">
  <thead>
    <tr>
      <th scope="col">Product</th>
      <th scope="col">Quantity</th>
      <th scope="col">Remove</th>
      <th scope="col">Unit Price</th>
      <th scope="col">Price</th>
    </tr>
  </thead>
  <tbody>
{% for item in cart %}
	{% with product=item.product %}
		<tr>
			<td>{{ product.name }}</td>
			<td>
				<form action="{% url 'cart:cart_add' product.id %}" method="post">
					{{ item.update_quantity_form.quantity }}
					{{ item.update_quantity_form.update }}
					<input type="submit" value="update">
					{% csrf_token %}
				</form>
			</td>
			<td><a href="{% url 'cart:cart_remove' product.id %}">Remove</a></td>
			<td>{{ item.price }}</td>
			<td>{{ item.total_price }}</td>
		</tr>
	{% endwith %}
{% endfor %}
<tr>
	<td colspan="4">Total Price</td>
	<td>{{ cart.get_total_price }}</td>
</tr>
  </tbody>
</table>

<a href="{% url 'shop:product_list' %}" class="btn btn-outline-info">Contiue Shopping</a>
<a href="#" class="btn btn-outline-info">Checkout</a>
{% endblock %}

shop/templates/shop/base.html
{% load humanize %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

    <title>{% block title %}{% endblock %}</title>
  </head>
  <body>
    {% block content %}

    {% endblock %}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
  </body>
</html>

shop/templates/shop/product/detail.html
{% extends 'shop/base.html' %}
{% block title %}
	{{ product.name }}
{% endblock %}

{% block content %}

<div class="container">
	<br><br><br><br>
<div class="card col-lg-8">
  <div class="row no-gutters">
    <div class="col-md-4">
      <img src="{{ product.image.url }}" class="card-img" alt="...">
    </div>
    <div class="col-md-8">
      <div class="card-body">
        <h5 class="card-title">{{ product.name }}</h5>
        <a href="{{ product.category.get_absolute_url }}">{{ product.category }}</a>
        <p class="card-text">{{ product.price }} MMK<br>{{ product.description }}</p>

        <p class="card-text"><small class="text-muted">{{ product.updated|timesince }} ago</small></p>
<form action="{% url 'cart:cart_add' product.id %}" method="post">
  {{ cart_product_form }}
  {% csrf_token %}
  <input type="submit" value="Add to cart">
</form>
      </div>
    </div>
  </div>
</div>	
</div>


{% endblock %} 

shop/templates/shop/product/list.html
{% extends 'shop/base.html' %}

{% block title %}
{{ category.name }} - Products
{% endblock %}

{% block content %}

<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="{% url 'shop:product_list' %}">Spring</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          All Items
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
        {% for c in categories %}
          <a class="dropdown-item" href="{{ c.get_absolute_url }}">{{ c.name }}</a>
        {% endfor %}
        </div>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0 ml-auto">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>
<div>
{% with total_items=cart|length %}
  {% if cart|length > 0 %}
    Your cart : <a href="{% url 'cart:cart_detail' %}">
      {{ total_items }} item{{ total_items|pluralize }}, {{ cart.get_total_price }} MMK
    </a>
  {% else %}
    Your cart is empty.
  {% endif %}
{% endwith %}  
</div>

<br>

<div class="container">
	<div class="row">

{% for product in products %}
	<div class="col-lg-4">
	<div class="card" style="width: 18rem;">
	  <img src="{{ product.image.url }}" class="card-img-top" alt="...">
	  <div class="card-body">
	    <h5 class="card-title">{{ product.name }}</h5>
	    <p class="card-text">{{ product.price }}</p>
	    <a href="{{ product.get_absolute_url }}" class="btn btn-primary">View Detail</a>
	  </div>
	</div>
	</div>
{% endfor %}

	</div>
</div>




{% endblock %}